/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestiondecontacto.vistas;

import com.mycompany.gestiondecontacto.clases.Tipo;
import com.mycompany.gestiondecontacto.clases.JsonManagerTipo;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VistaTipo extends javax.swing.JFrame {

    /**
     * Creates new form VistaTipo
     */
    private final JsonManagerTipo tipoManager = new JsonManagerTipo();
    private ArrayList<Tipo> tipos;
    DefaultTableModel modelo;
    static int codigo = 1;
    VistasContacto vt;
    

    public ImageIcon scaleImage(ImageIcon icon, int w, int h) {
        Image img = icon.getImage();
        Image newing = img.getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(newing);
    }

    public VistaTipo(ArrayList<Tipo> tipos, VistasContacto vt) {
        
        initComponents();
        this.vt = vt;
        if (tipos == null) {
            this.tipos = new ArrayList<>(); 
        } else {
            this.tipos = tipos;
        } 

// 1. Inicializar la variable de clase 'this.modelo'
        this.modelo = new DefaultTableModel();
        this.modelo.addColumn("CODIGO");
        this.modelo.addColumn("TIPO DE CONTACTO");
        // 4. Asignar el modelo a la JTable
        jtDatos.setModel(this.modelo); 
        this.codigo = obtenerSiguienteCodigoDisponoble(this.tipos);
        
        mostrarDatos(); // Esta llamada estaba en la línea ~86

        String imagePath = "/img/comportamiento-del-cliente.png";
        java.net.URL location = getClass().getResource(imagePath);

        // Verifica si se encontró el recurso
        if (location == null) {
            System.err.println("¡ERROR FATAL DE RUTA! No se encontró el recurso: " + imagePath);
            // Opcional: Mostrar una imagen de placeholder o dejar el JLabel vacío
        } else {
            int width = 100; // Ajusta el ancho deseado
            int height = 100; // Ajusta el alto deseado

            ImageIcon originalIcon = new ImageIcon(location);

            if (originalIcon.getImage() != null) {
                ImageIcon scaledIcon = scaleImage(originalIcon, width, height);

                // ¡CAMBIA 'jLabel1' POR EL NOMBRE REAL DE TU COMPONENTE DE IMAGEN EN VistaTipo!
                jLabel1.setIcon(scaledIcon);
                jLabel1.setText("");
            } else {
                System.err.println("Error: Imagen cargada, pero no se pudo obtener el contenido.");
            }
        }

        this.tipos = tipos;
        this.vt = vt;

        this.vt.setVisible(false);
        modelo = new DefaultTableModel();
        this.codigo = obtenerSiguienteCodigoDisponoble(tipos);
        modelo.addColumn("CODIGO");
        modelo.addColumn("TIPO DE CONTACTO");
        mostrarDatos();
        jtDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDatosMouseClicked(evt);
            }
        });
    }

    public void setTipos(ArrayList<Tipo> nuevosTipos) {
        this.tipos = nuevosTipos;
    }

    private int obtenerSiguienteCodigoDisponoble(ArrayList<Tipo> tipos) {
        int maxCodigo = 0;
        for (Tipo t : tipos) {
            if (t.getCodigo() > maxCodigo) {
                maxCodigo = t.getCodigo();
            }
        }
        return maxCodigo + 1;
    }

    public void mostrarDatos() {
        modelo.setNumRows(tipos.size());
        for (int i = 0; i < tipos.size(); i++) {
            modelo.setValueAt(tipos.get(i).getCodigo(), i, 0);
            modelo.setValueAt(tipos.get(i).getNombre(), i, 1);
        }
        jtDatos.setModel(modelo);
    }

    private void jtDatosMouseClicked(java.awt.event.MouseEvent evt) {
        // Obtiene el índice de la fila seleccionada
        int filaSeleccionada = jtDatos.getSelectedRow();

        if (filaSeleccionada >= 0) {
            // Obtiene el objeto Tipo completo de la lista `tipos`
            Tipo tipoSeleccionado = this.tipos.get(filaSeleccionada);

            // Muestra el nombre (tipo) en el campo de texto
            tfTipo.setText(tipoSeleccionado.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        tfTipo = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDatos = new javax.swing.JTable();
        button3 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("TYPE:");

        button1.setLabel("ELIMINATE");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("SAVE");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        jtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtDatos);

        button3.setLabel("BACK");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comportamiento-del-cliente.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //boton numero 1
    //este es para eliminar 
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if (jtDatos.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "SELECIONE EL REGISTRO PARA ELIMINAR");

        } else {
            this.tipos.remove(this.jtDatos.getSelectedRow());
            this.tipoManager.guardarTipos(this.tipos);
            this.mostrarDatos();
            JOptionPane.showMessageDialog(null, "Tipo eliminado con exito");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        String nuevoNombre = tfTipo.getText();
        int filaSeleccionada = jtDatos.getSelectedRow();

        if (nuevoNombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "INGRESE LOS DATOS");
            return; // Sale del método si el campo está vacío
        }

        if (filaSeleccionada >= 0) {
            // Lógica de MODIFICACIÓN
            Tipo t = this.tipos.get(filaSeleccionada);
            t.setNombre(nuevoNombre);

            JOptionPane.showMessageDialog(null, "Tipo modificado con éxito");

        } else {
            // Lógica de AÑADIR NUEVO
            Tipo t = new Tipo();
            t.setCodigo(codigo);
            codigo++;
            t.setNombre(nuevoNombre);
            this.tipos.add(t);

            JOptionPane.showMessageDialog(null, "Tipo añadido con éxito");
        }

        // Limpia el campo de texto y actualiza la tabla
        tfTipo.setText("");
        mostrarDatos();

        // **OPCIONAL PERO RECOMENDADO:** Reiniciar la selección de la tabla
        jtDatos.clearSelection();
        this.tipoManager.guardarTipos(this.tipos);
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        this.vt.setTipos(this.tipos);
        this.tipoManager.guardarTipos(this.tipos);
        this.dispose();
        this.vt.setVisible(true);
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtDatos;
    private java.awt.Label label1;
    private java.awt.TextField tfTipo;
    // End of variables declaration//GEN-END:variables
}
