/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestiondecontacto.vistas;

import com.mycompany.gestiondecontacto.clases.Contacto;
import com.mycompany.gestiondecontacto.clases.Numero;
import com.mycompany.gestiondecontacto.clases.Tipo;
import java.awt.HeadlessException;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.DefaultComboBoxModel;

public class VistaNumeros extends javax.swing.JFrame {

    /**
     * Creates new form VistaNumeros
     */
    private VistasContacto vistaPrincipal;
    private  Contacto c;
    DefaultTableModel modelo;
    ArrayList<Tipo> tipos;
    int codigo;
    
    

    public VistaNumeros() throws HeadlessException {
    }
    public ImageIcon scaleImage(ImageIcon icon, int w, int h){
        Image img = icon.getImage();
        Image newing = img.getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(newing);
    }

    public VistaNumeros(Contacto c, VistasContacto vc, ArrayList<Tipo> tipos) {
        
        
        
        initComponents();
        
        
        String imagePath = "/img/telefono-inteligente.png"; // <-- Confirma esta ruta en tu carpeta 'img'
    java.net.URL location = getClass().getResource(imagePath);
    
    // Verifica si se encontró el recurso (para evitar el NullPointerException)
    if (location == null) {
        System.err.println("¡ERROR FATAL DE RUTA! No se encontró el recurso: " + imagePath);
    } else {
        int width = 100; // Ajusta el ancho deseado
        int height = 100; // Ajusta el alto deseado
        
        ImageIcon originalIcon = new ImageIcon(location);
        
        if (originalIcon.getImage() != null) {
            ImageIcon scaledIcon = scaleImage(originalIcon, width, height);
            
            // ¡CAMBIA 'jLabel1' POR EL NOMBRE REAL DE TU COMPONENTE DE IMAGEN EN VistaNumeros!
            // Si no tienes jLabel1, debes añadirlo en el diseñador.
            // Si el componente de imagen existe, el código generado por NetBeans debe asignarle un nombre (ej. jLabel1)
            jLabel1.setIcon(scaledIcon); 
            jLabel1.setText(""); 
        } else {
            System.err.println("Error: Imagen cargada, pero no se pudo obtener el contenido.");
        }
    }
        this.c = c;
        this.vistaPrincipal = vc;
        //this.vc.setVisible(false);
        this.tipos = tipos;
        this.codigo = ObtenerSiguienteCodigoDisponible();
        modelo = new DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("NUMERO");
        modelo.addColumn("TIPO DECONTACTO");
        this.jlContacto.setText(c.getNombre() + " " + c.getApellido());

        jcCombo.addItem("SELECIONE");
        for (int i = 0; i < this.tipos.size(); i++) {
            jcCombo.addItem(this.tipos.get(i).getNombre());
        }
        jcCombo.addItem("SELECIONE");
        if (this.tipos != null) { // <--- ¡Esta es la corrección clave!
            for (int i = 0; i < this.tipos.size(); i++) {
                jcCombo.addItem(this.tipos.get(i).getNombre());
            }
        } else {
            // Opcional: Mostrar un mensaje si la lista de tipos no se pudo cargar
            JOptionPane.showMessageDialog(this, "Error: La lista de Tipos no se pudo cargar.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
        }
        setLocationRelativeTo(null);
        mostrarDatos();
        tfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                // Permite solo dígitos (0-9) y backspace/delete
                if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
                    evt.consume(); // Ignora el caracter
                }
            }
        });
    }

    public void mostrarDatos() {
        modelo.setNumRows(this.c.getNumeros().size());
        for (int i = 0; i < this.c.getNumeros().size(); i++) {
            modelo.setValueAt(this.c.getNumeros().get(i).getCodigo(), i, 0);
            modelo.setValueAt(this.c.getNumeros().get(i).getNumero(), i, 1);
            modelo.setValueAt(this.c.getNumeros().get(i).getTipo().getNombre(), i, 2);
        }
        jtDatos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jlContacto = new java.awt.Label();
        tfNumero = new java.awt.TextField();
        jcCombo = new javax.swing.JComboBox<>();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDatos = new javax.swing.JTable();
        button3 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("CONTAC:");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 145, 88, 44));

        label2.setText("TYPE:");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 253, 88, 44));

        label3.setText("NUMBER:");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 199, 88, 44));
        jPanel1.add(jlContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 155, 264, -1));

        tfNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(tfNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 213, 234, -1));

        jPanel1.add(jcCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 275, 234, -1));

        button1.setLabel("ELIMINATE");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 324, 76, 40));

        button2.setLabel("SAVE");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 324, 76, 40));

        jtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 389, 402, 220));

        button3.setLabel("CANCEL");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 629, 85, 33));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefono-inteligente.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 20, 121, 115));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//este es para guardar
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        // 1. Obtención y Validación de Datos
        String numeroTexto = tfNumero.getText().trim();
        // Obtener el objeto Tipo directamente del JComboBox
        // Nota: El primer elemento del JComboBox (índice 0) suele ser "SELECCIONE", por eso revisamos el índice.
        int indiceTipoSeleccionado = jcCombo.getSelectedIndex();

        // 2. Validación de Campos
        boolean esNumeroValido = numeroTexto.matches("\\d+") && numeroTexto.length() >= 6;
        boolean tipoSeleccionado = indiceTipoSeleccionado > 0;

        if (esNumeroValido && tipoSeleccionado) {

            // El tipo real en la lista 'this.tipos' está en el índice del JComboBox menos 1.
            Tipo tipo = this.tipos.get(indiceTipoSeleccionado - 1);

            // 3. Crear el nuevo objeto Numero
            Numero n = new Numero();

            // Se recomienda obtener el siguiente código disponible de la lista de números del contacto
            // si no quieres que el código del número se mezcle con el código del contacto.
            // Aquí uso la variable 'codigo' de tu clase, asumiendo que la manejas globalmente.
            n.setCodigo(codigo);
            codigo++;

            // 4. Establecer el número y el tipo
            n.setNumero(numeroTexto);
            n.setTipo(tipo); // Asignación directa del objeto Tipo

            // 5. Agregar a la lista del Contacto (this.c es el Contacto seleccionado)
            if (this.c.getNumeros() == null) {
                this.c.setNumeros(new ArrayList<>());
            }
            this.c.getNumeros().add(n);

            // 6. Limpiar y actualizar
            tfNumero.setText("");
            jcCombo.setSelectedIndex(0); // Regresar a "SELECCIONE"
            this.mostrarDatos();

            JOptionPane.showMessageDialog(this, "Número agregado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } else {
            // Manejo de errores más claro
            String mensaje = "";
            if (!tipoSeleccionado) {
                mensaje = "Por favor, seleccione un Tipo de Contacto.";
            } else if (!numeroTexto.matches("\\d+")) {
                mensaje = "El número solo debe contener dígitos (0-9).";
            } else if (numeroTexto.length() < 6) {
                mensaje = "El número debe tener al menos 6 dígitos.";
            } else {
                // Caso de error por si algo más falló
                mensaje = "Error al ingresar los datos.";
            }

            JOptionPane.showMessageDialog(this, mensaje, "Error de Validación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if (jtDatos.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "SELECION PARA ELIMINAR");

        } else {
            this.c.getNumeros().remove(jtDatos.getSelectedRow());
            this.mostrarDatos();
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        this.vistaPrincipal.forzaGuardadoContacto();
        
        this.dispose();
        this.vistaPrincipal.setVisible(true);
    }//GEN-LAST:event_button3ActionPerformed

    private void tfNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcCombo;
    private java.awt.Label jlContacto;
    private javax.swing.JTable jtDatos;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField tfNumero;
    // End of variables declaration//GEN-END:variables

    private int ObtenerSiguienteCodigoDisponible() {
        int maxCodigo = 0;
        if (this.c.getNumeros() != null) {
            for (Numero num : this.c.getNumeros()) {
                if (num.getCodigo() > maxCodigo) {
                    maxCodigo = num.getCodigo();
                }
            }
        }
        return maxCodigo + 1;
    }
}
