/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestiondecontacto.vistas;

import com.mycompany.gestiondecontacto.clases.Contacto;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class VistaModificar extends javax.swing.JFrame {

    /**
     * Creates new form VistaModificar
     */
    Contacto c;
    VistasContacto vc;

    public ImageIcon scaleImage(ImageIcon icon, int w, int h) {
        Image img = icon.getImage();
        Image newimg = img.getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(newimg);

    }

    public VistaModificar(Contacto c, VistasContacto vc) {
        initComponents();
        int width = 80;
        int height = 80;
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/img/la-configuracion-de-privacidad.png")); 

        if (originalIcon.getImage() != null) {
            ImageIcon scaledIcon = scaleImage(originalIcon, width, height);
            // Suponiendo que el JLabel donde va la imagen se llama 'jLabel1'
            // ¡CAMBIA 'jLabel1' POR EL NOMBRE REAL DE TU COMPONENTE DE IMAGEN!
            jLabel1.setIcon(scaledIcon);
            jLabel1.setText(""); // Opcional: Eliminar cualquier texto por defecto del JLabel
        } else {
            System.err.println("Error: No se pudo cargar la imagen para VistaModificar.");
        }
        this.c = c;
        this.vc = vc;
        vc.setVisible(false);
        jlCodigo.setText(String.valueOf(c.getCodigo()));
        tfNombre.setText(c.getNombre());
        tfApellido.setText(c.getApellido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jlCodigo = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        tfNombre = new java.awt.TextField();
        tfApellido = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("CODE:");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 127, -1, -1));
        jPanel1.add(jlCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 127, 270, -1));

        label2.setText("LAST NAME:");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 213, -1, -1));

        label3.setText("NAME:");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 169, -1, -1));
        jPanel1.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 169, 270, -1));
        jPanel1.add(tfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 213, 270, -1));

        button1.setLabel("CANCEL");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 266, 84, 39));

        button2.setLabel("SAVE");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 266, 84, 39));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/la-configuracion-de-privacidad.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 29, 118, 88));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.vc.setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if (!tfNombre.getText().equals("") && !tfApellido.getText().equals("")) {
            this.c.setNombre(tfNombre.getText());
            this.c.setApellido(tfApellido.getText());
            this.dispose();
            this.vc.setVisible(true);
            this.vc.mostrarDatos();
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE LOS DATOS");
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label jlCodigo;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField tfApellido;
    private java.awt.TextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
